[package]
name = "synth"
version = "0.1.0"
authors = ["kujon <jakub.korzeniowski@vortexa.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
